<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VijayTYSS" failures="2" tests="9" name="Test" time="0.161" errors="0" timestamp="2023-10-19T12:33:43 IST">
  <testcase classname="retryLogic.retryCheck" name="test1" time="0.028">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryLogic.retryCheck" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryLogic.retryCheck" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="retryLogic.retryCheck" name="test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.retryCheck.test1(retryCheck.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="retryLogic.retryCheck" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryLogic.retryCheck" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryLogic.retryCheck" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="retryLogic.retryCheck" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.retryCheck.test2(retryCheck.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="retryLogic.retryCheck" name="test3" time="0.001"/>
</testsuite> <!-- Test -->
